@extends('layouts.app')
@section('title','Pinjaman')
@section('content')
<div class="page-heading"><div><p class="eyebrow">PINJAMAN</p><h1>Portofolio Pinjaman</h1><p>Kelola pengajuan, approval, pencairan, angsuran, dan kualitas pinjaman.</p></div><button class="btn btn-primary">＋ Pengajuan Pinjaman</button></div>
<div class="pipeline">
    <div><span class="pipe-icon">1</span><small>Pengajuan</small><strong>{{ $loans->count() }}</strong></div><i></i><div><span class="pipe-icon">2</span><small>Verifikasi</small><strong>2</strong></div><i></i><div><span class="pipe-icon">3</span><small>Approval</small><strong>{{ $loans->where('status','Menunggu Approval')->count() }}</strong></div><i></i><div><span class="pipe-icon">4</span><small>Pencairan</small><strong>1</strong></div><i></i><div><span class="pipe-icon done">✓</span><small>Aktif</small><strong>{{ $loans->whereIn('status',['Aktif','Tunggakan'])->count() }}</strong></div>
</div>
<div class="card"><div class="toolbar"><div class="search-box">⌕ <input data-table-search="#loanTable" placeholder="Cari nomor pinjaman atau anggota..."></div><select><option>Semua Status</option><option>Aktif</option><option>Tunggakan</option><option>Menunggu Approval</option></select></div><div class="table-wrap"><table class="data-table" id="loanTable"><thead><tr><th>Pinjaman</th><th>Anggota</th><th>Produk</th><th>Tenor</th><th class="right">Plafon</th><th class="right">Outstanding</th><th>Status</th><th></th></tr></thead><tbody>@foreach($loans as $loan)@php($badge=$loan->status==='Tunggakan'?'danger':($loan->status==='Menunggu Approval'?'warning':($loan->status==='Lunas'?'neutral':'success')))<tr><td><strong>{{ $loan->loan_no }}</strong><small class="block">{{ $loan->applied_at->format('d M Y') }}</small></td><td><a class="table-link" href="{{ route('members.show',$loan->member) }}">{{ $loan->member->name }}</a><small class="block">{{ $loan->member->member_no }}</small></td><td>{{ $loan->product }}</td><td>{{ $loan->term_months }} bln <small class="block">{{ number_format($loan->interest_rate,1,',','.') }}%</small></td><td class="right">Rp {{ number_format($loan->principal,0,',','.') }}</td><td class="right"><strong>Rp {{ number_format($loan->outstanding,0,',','.') }}</strong></td><td><span class="badge {{ $badge }}">{{ $loan->status }}</span></td><td class="right"><button class="row-action">⋯</button></td></tr>@endforeach</tbody></table></div></div>
@endsection
