<?php $__env->startSection('title','Pinjaman'); ?>
<?php $__env->startSection('content'); ?>
<div class="page-heading"><div><p class="eyebrow">PINJAMAN</p><h1>Portofolio Pinjaman</h1><p>Kelola pengajuan, approval, pencairan, angsuran, dan kualitas pinjaman.</p></div><button class="btn btn-primary">＋ Pengajuan Pinjaman</button></div>
<div class="pipeline">
    <div><span class="pipe-icon">1</span><small>Pengajuan</small><strong><?php echo e($loans->count()); ?></strong></div><i></i><div><span class="pipe-icon">2</span><small>Verifikasi</small><strong>2</strong></div><i></i><div><span class="pipe-icon">3</span><small>Approval</small><strong><?php echo e($loans->where('status','Menunggu Approval')->count()); ?></strong></div><i></i><div><span class="pipe-icon">4</span><small>Pencairan</small><strong>1</strong></div><i></i><div><span class="pipe-icon done">✓</span><small>Aktif</small><strong><?php echo e($loans->whereIn('status',['Aktif','Tunggakan'])->count()); ?></strong></div>
</div>
<div class="card"><div class="toolbar"><div class="search-box">⌕ <input data-table-search="#loanTable" placeholder="Cari nomor pinjaman atau anggota..."></div><select><option>Semua Status</option><option>Aktif</option><option>Tunggakan</option><option>Menunggu Approval</option></select></div><div class="table-wrap"><table class="data-table" id="loanTable"><thead><tr><th>Pinjaman</th><th>Anggota</th><th>Produk</th><th>Tenor</th><th class="right">Plafon</th><th class="right">Outstanding</th><th>Status</th><th></th></tr></thead><tbody><?php $__currentLoopData = $loans; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $loan): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php ($badge=$loan->status==='Tunggakan'?'danger':($loan->status==='Menunggu Approval'?'warning':($loan->status==='Lunas'?'neutral':'success'))); ?><tr><td><strong><?php echo e($loan->loan_no); ?></strong><small class="block"><?php echo e($loan->applied_at->format('d M Y')); ?></small></td><td><a class="table-link" href="<?php echo e(route('members.show',$loan->member)); ?>"><?php echo e($loan->member->name); ?></a><small class="block"><?php echo e($loan->member->member_no); ?></small></td><td><?php echo e($loan->product); ?></td><td><?php echo e($loan->term_months); ?> bln <small class="block"><?php echo e(number_format($loan->interest_rate,1,',','.')); ?>%</small></td><td class="right">Rp <?php echo e(number_format($loan->principal,0,',','.')); ?></td><td class="right"><strong>Rp <?php echo e(number_format($loan->outstanding,0,',','.')); ?></strong></td><td><span class="badge <?php echo e($badge); ?>"><?php echo e($loan->status); ?></span></td><td class="right"><button class="row-action">⋯</button></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\ASUS\Herd\koperasi-finance\resources\views/loans/index.blade.php ENDPATH**/ ?>