<?php $__env->startSection('title','Simpanan'); ?>
<?php $__env->startSection('content'); ?>
<div class="page-heading"><div><p class="eyebrow">SIMPANAN</p><h1>Rekening Simpanan</h1><p>Pantau saldo dan rekening simpanan seluruh anggota.</p></div><div class="heading-actions"><button class="btn btn-light">Rekening Koran</button><button class="btn btn-primary">＋ Setoran</button></div></div>
<div class="kpi-grid three">
<?php $__currentLoopData = ['Pokok'=>'blue','Wajib'=>'green','Sukarela'=>'purple']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type=>$color): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<div class="kpi-card"><div class="kpi-icon <?php echo e($color); ?>">◫</div><div><span>Simpanan <?php echo e($type); ?></span><strong>Rp <?php echo e(number_format(($summary[$type] ?? 0)/1000000,1,',','.')); ?> Jt</strong><small class="muted"><?php echo e($savings->where('type',$type)->count()); ?> rekening</small></div></div>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</div>
<div class="card"><div class="toolbar"><div class="search-box">⌕ <input data-table-search="#savingsTable" placeholder="Cari rekening atau anggota..."></div><select><option>Semua Jenis</option><option>Pokok</option><option>Wajib</option><option>Sukarela</option></select></div><div class="table-wrap"><table class="data-table" id="savingsTable"><thead><tr><th>Rekening</th><th>Anggota</th><th>Jenis</th><th>Cabang</th><th class="right">Saldo</th><th>Status</th></tr></thead><tbody><?php $__currentLoopData = $savings; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $saving): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><strong><?php echo e($saving->account_no); ?></strong></td><td><a class="table-link" href="<?php echo e(route('members.show',$saving->member)); ?>"><?php echo e($saving->member->name); ?></a><small class="block"><?php echo e($saving->member->member_no); ?></small></td><td>Simpanan <?php echo e($saving->type); ?></td><td><?php echo e($saving->member->branch); ?></td><td class="right"><strong>Rp <?php echo e(number_format($saving->balance,0,',','.')); ?></strong></td><td><span class="badge success">Aktif</span></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\ASUS\Herd\koperasi-finance\resources\views/savings/index.blade.php ENDPATH**/ ?>